GPU_ID: 0
BASE_TASK_CONFIG_PATH: "exp_configs/obj_mp3d-val.yaml"
TRAINER_NAME: "custom_ddppo"
ENV_NAME: "CustomObjectNavRLEnv-val"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "eval-logs/dist-6/tb"
VIDEO_DIR: "eval-logs/dist-6/videos"
TEST_EPISODE_COUNT: 50
EVAL_CKPT_PATH_DIR: "exp-ckpts_b/Eval-ckpts/dist-6"
NUM_PROCESSES: 4
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
CHECKPOINT_FOLDER: "exp-ckpts_b/dist-6"
NUM_UPDATES: 100000000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 1000
VIS_INTERVAL: 200
RL:
  REWARD_SHAPE: "dist"
  REWARD_RATIO: 1.0
  SUCCESS_REWARD: 5.0
  SLACK_REWARD: 0.01
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-6
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 64
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 10

    use_normalized_advantage: False

    hidden_size: 512

  DDPPO:
    use_midlevel_reps: False
    midreps_size: 2
    use_pretrained_resnet : False
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/new_checkpoints/ckpt.42.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: False
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: True
    # Whether or not to reset the critic linear layer
    reset_critic: False

    # Model parameters
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2
